---
title: "useful.lovetoken package in R"
output:
  html_document:
    fig_height: 7
    toc: yes
    toc_float: yes
    keep_md: yes
---

<style type="text/css">@import url("https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css")</style>

```{r env, echo=F, message=FALSE, warning=FALSE}
## load packages
pacman::p_load("pacman", "dplyr", "knitr", "rmarkdown", "useful.lovetoken")

## global option
opts_chunk$set(fig.align = "center", warning = F, message = F) # for knitr
set.seed(1004)
```

# Overview

자주사용하는 사용자 정의 함수를 모은 저만의 패키지 입니다.

# Example

```{r}
library(useful.lovetoken)
```

## `paste2()`

`paste0()` 과 다르게 NA 를 문자열로 인지하지 않고 paste 를 수행합니다.  

```{r}
A <- "Hello "
B <- c("world", "world!", NA)
paste0(A, B)
paste2(A, B)
```

## `psum()`

```{r}
sum(1:5, c(1, 2, 3, 4, NA), c(1, NA, 3, 4, 5), na.rm = T)
psum(1:5, c(1, 2, 3, 4, NA), c(1, NA, 3, 4, 5), na.rm = T)
```

## `which_matrix()`

```{r}
(m <- matrix(sample(c(T,F), 30, T), 5, 6))
which(m)
which_matrix(m)
```

## `trim()`

정규표현식를 이용하여 공백문자에 대한 trimming 을 제공합니다.  

```{r}
trim("  Wow!  ", "leading")
trim("  Wow!  ", "trailing")
```

## `swap()`

```{r eval = F}
x <- 1
y <- 2
swap("x", "y")
cat(x, y)
```

```
## 2 1
```

# Install

```{r eval=F}
devtools::install_github("lovetoken/useful.lovetoken")
```

# License

[GPL-3](https://www.gnu.org/licenses/gpl-3.0.en.html)
